<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by sas-softwares@procergs.rs.gov.br (PROCERGS) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.portalfiscal.inf.br/bpe" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" targetNamespace="http://www.portalfiscal.inf.br/bpe" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="tiposGeralBPe_v1.00.xsd"/>
	<xs:complexType name="TBPeConsultaDFe">
		<xs:annotation>
			<xs:documentation>Tipo Pedido de Consulta do Bilhete de Passagem Eletrônico</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="tpAmb" type="TAmb">
				<xs:annotation>
					<xs:documentation>Identificação do Ambiente:
1 - Produção
2 - Homologação</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="xServ" type="TServ" fixed="CONSULTAR">
				<xs:annotation>
					<xs:documentation>Serviço Solicitado</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="chBPe" type="TChDFe">
				<xs:annotation>
					<xs:documentation>Chaves de acesso do BP-e, compostas por: UF do emitente, AAMM da emissão do BP-e, CNPJ do emitente, modelo, série e número do MDF-e e código numérico + DV.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="versao" type="TVerBPeConsultaDFe" use="required"/>
	</xs:complexType>
	<xs:complexType name="TRetBPeConsultaDFe">
		<xs:annotation>
			<xs:documentation>Tipo Retorno de Pedido de Consulta do Bilhete de Passagem Eletrônico</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="tpAmb" type="TAmb">
				<xs:annotation>
					<xs:documentation>Identificação do Ambiente:
1 - Produção
2 - Homologação</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="verAplic" type="TVerAplic">
				<xs:annotation>
					<xs:documentation>Versão do Aplicativo que processou a consulta do BP-e</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="cStat" type="TStat">
				<xs:annotation>
					<xs:documentation>Código do status da consulta do BP-e</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="xMotivo" type="TMotivo">
				<xs:annotation>
					<xs:documentation>Descrição literal do status da consulta do BP-e</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="BPeDFe" type="TBPeDFe" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="versao" type="TVerBPeConsultaDFe" use="required"/>
	</xs:complexType>
	<xs:complexType name="TBPeDFe">
		<xs:annotation>
			<xs:documentation>Tipo Documento Fiscal Eletrônico BP-e</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="procBPe">
				<xs:complexType>
					<xs:sequence minOccurs="2" maxOccurs="2">
						<xs:any>
							<xs:annotation>
								<xs:documentation>Autorização de Uso do BP-e</xs:documentation>
							</xs:annotation>
						</xs:any>
					</xs:sequence>
					<xs:attribute name="versao" type="TVerProcBPe" use="required"/>
					<xs:attribute name="ipTransmissor" type="TIPv4" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="procEventoBPe" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="2" maxOccurs="2">
						<xs:any>
							<xs:annotation>
								<xs:documentation>Demais eventos vinculados ao BP-e</xs:documentation>
							</xs:annotation>
						</xs:any>
					</xs:sequence>
					<xs:attribute name="versao" type="TVerProcBPe" use="required"/>
					<xs:attribute name="ipTransmissor" type="TIPv4" use="optional"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="TVerBPeConsultaDFe">
		<xs:annotation>
			<xs:documentation> Tipo Versão do Consulta DFe de BP-e - 1.00</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="1\.00"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TVerProcBPe">
		<xs:annotation>
			<xs:documentation> Tipo Versão do Consulta Proc de BP-e</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="1.00"/>
			<xs:enumeration value="3.00"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
