<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.portalfiscal.inf.br/nfe" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" targetNamespace="http://www.portalfiscal.inf.br/nfe" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="tiposBasico_v1.03.xsd"/>
	<xs:element name="detEvento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="descEvento"/>
				<xs:element ref="cOrgaoAutor"/>
				<xs:element ref="cPostoUF"/>
				<xs:element ref="xPostoUF"/>
				<xs:element ref="CPFOper"/>
				<xs:element ref="xNomeOper"/>
				<xs:element ref="nProt"/>
				<xs:element ref="xJust"/>
			</xs:sequence>
			<xs:attribute name="versao" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:whiteSpace value="preserve"/>
						<xs:enumeration value="1.00"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="descEvento">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="preserve"/>
				<xs:enumeration value="Cancelamento Registro Passagem NFe"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="cOrgaoAutor" type="TCOrgaoIBGE"/>
	<xs:element name="cPostoUF">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="preserve"/>
				<xs:pattern value="[0-9]{4}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="xPostoUF">
		<xs:simpleType>
			<xs:restriction base="TString">
				<xs:minLength value="2"/>
				<xs:maxLength value="60"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CPFOper" type="TCpf"/>
	<xs:element name="xNomeOper">
		<xs:simpleType>
			<xs:restriction base="TString">
				<xs:minLength value="2"/>
				<xs:maxLength value="60"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="nProt" type="TProt"/>
	<xs:element name="xJust">
		<xs:simpleType>
			<xs:restriction base="TString">
				<xs:minLength value="1"/>
				<xs:maxLength value="255"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>
